export const movies = [
    {
      id: 1,
      title: "The Avengers",
      price: 199,
      plot: "Earth's mightiest heroes must come together and learn to fight as a team if they are going to stop the mischievous Loki and his alien army from enslavinf humanity.",
      rating: 8.9,
      stars: 0,
      url: "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
      fav: true,
      cart: true,
      isInCart:false,
    },
    {
      id: 2,
      title: "Justice League",
      price: 199,
      plot: "Super hero movie",
      rating: 8.9,
      stars: 0,
      url: "https://m.media-amazon.com/images/M/MV5BYWVhZjZkYTItOGIwYS00NmRkLWJlYjctMWM0ZjFmMDU4ZjEzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_FMjpg_UX1000_.jpg",
      fav: true,
      cart: true,
      isInCart:false,
    },
    {
      id: 3,
      title: "Sucide Squad",
      price: 199,
      plot: "Super hero movie",
      rating: 8.9,
      stars: 0,
      url: "https://m.media-amazon.com/images/M/MV5BMjM1OTMxNzUyM15BMl5BanBnXkFtZTgwNjYzMTIzOTE@._V1_.jpg",
      fav: true,
      cart: true,
      isInCart:false,
    },
  ]